export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="gentoo"
CASE_SENSITIVE="true"
ENABLE_CORRECTION="true"
HIST_STAMPS="dd/mm/yyyy"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8
export EDITOR='nvim'

alias vim="nvim"

export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

export VCPKG_ROOT="$HOME/.vcpkg"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

autoload bashcompinit
bashcompinit

